function p = vehicle_params(mode)
% VEHICLE_PARAMS  Build the params struct p for the active car. SI unless noted.
%   p = vehicle_params()             full car, grip loaded from tire_coeffs_<CAR>.mat
%   p = vehicle_params('bootstrap')  car only, grip NaN (used by the tire fits)
%
% p is assembled from:
%   cars/config_<CAR>.m    every property of the car (vd_car selects which)
%   this file              universal constants, competition scenario,
%                          model-fidelity switches, default camber
%   tire_coeffs_<CAR>.mat  the fitted tire (generated by build_tire_coeffs)
%   util/vd_derive.m       every derived quantity
% To change the car, edit its config, or use vd_set for a one-off "what if?".
% Do not put car properties in this file.

if nargin < 1, mode = 'full'; end
bootstrap = strcmpi(mode, 'bootstrap');

% ======================= INPUTS =========================================

% --- Car config (see vd_car.m / cars/) ---
p.car = vd_car();
cfg = feval(['config_' p.car]);
for f = fieldnames(cfg)', p.(f{1}) = cfg.(f{1}); end

% --- Config contract ----------------------------------------------------
% Every field the models expect a car to supply. A config that misses one
% fails here instead of silently inheriting a default.
REQUIRED = { ...
  'm_car','m_driver','m_driver_min','m_driver_max','mass_dist_f','h_cg', ...
  'f_unsprung','unsprung_f','L','t_f','t_r', ...
  'tire_id','tire_data_prefix','mu_derate','lambda_Ca','Re', ...
  'ClA','CdA','LLTD','aero_df_front', ...
  'V_pack_nom','V_pack_max','I_pack_max','E_pack_Wh','I_fuse_main','R_pack', ...
  'motor_id','inverter_id','T_motor_max','T_motor_cont','rpm_motor_max','drive', ...
  'gear_ratio','eta_dt','eta_chain','eta_inv','Crr','k_trac', ...
  'b_driveline','Tc_driveline','DI','I_rotor','I_wheel','scenario','cooling','cell'};
missing = REQUIRED(~isfield(cfg, REQUIRED));
assert(isempty(missing), 'vehicle_params:incompleteConfig', ...
    'cars/config_%s.m is missing required field(s): %s', p.car, strjoin(missing, ', '));

% --- Environment (universal constants, not car properties) ---
p.g   = 9.81;      % gravity [m/s^2]
p.rho = 1.225;     % air density [kg/m^3]

% --- Competition scenario (same for every car) ---
p.scenario.endurance_m    = fsae_rules().endurance_m;  % rules endurance distance [m]
p.scenario.benchmark_laps = 22;     % lap count of the real 2026 results used for scoring [-]

% --- Model selection (fidelity switches, not car properties) ---
p.grip_model = 'axle';      % lateral limit: 'axle' (load-sensitive) | 'pointmass'
p.long_model = 'combined';  % longitudinal: 'combined' (per-axle ellipse) | 'axle' | 'pointmass'

% --- Per-corner camber (degrees, positive = the helpful lean) -------------
% Zero by default. An input, not a suspension model: nothing computes camber
% from geometry yet. fo/ro = front/rear OUTSIDE wheel, fi/ri = INSIDE. The
% inside wheel usually leans the opposite way, e.g.
%   vd_set(p, 'camber_deg', struct('fo', 1.5, 'fi', -1.5, 'ro', 1.5, 'ri', -1.5))
% targets/run_camber_targets.m sweeps it.
p.camber_deg = struct('fo', 0, 'fi', 0, 'ro', 0, 'ri', 0);

% ======================= LOADED (generated artifact) =====================
if bootstrap
    p.mu_y_raw      = NaN;
    p.mu_anisotropy = NaN;
    p.Ca_coef       = [NaN NaN NaN];
    p.mu_coef       = [NaN NaN];
    p.Fz_fit_max    = NaN;
    p.mu_hiload_slope = NaN;
    p.hiload_cov_lbf = NaN;
    p.Fz_outer_limit_lbf = NaN;
    p.mu_outer_central   = NaN;
    p.mu_outer_low       = NaN;
    p.shape6        = NaN;
    p.mu_y_18_peak  = NaN;
    p.mu_y_at6      = NaN;
    p.Fz_lat6       = NaN;
    p.mu_x_18       = NaN;
    p.n_env_drive   = NaN;
    p.n_env_brake   = NaN;
    p.mf_bin_Fz_lbf = [];
    p.mf_bin_B      = [];
    p.mf_bin_C      = [];
    p.mf_bin_E      = [];
    % Camber terms are zero (camber changes nothing), not NaN, so a fit that
    % touches the tire in bootstrap mode is not poisoned.
    p.camber_kD            = [0 0 0 0];
    p.camber_kC            = 0;
    p.camber_kS            = [0 0];
    p.camber_Fz_ref_lbf    = NaN;
    p.camber_Fz_min_lbf    = NaN;
    p.camber_Fz_max_lbf    = NaN;
    p.camber_gamma_max_deg = 0;
    p.camber_status        = 'bootstrap (no camber)';
    p.camber_basis         = 'bootstrap';
    p.tire_schema_version  = NaN;
    p.tire_basis    = 'bootstrap (no grip)';
    p.tire_src_hash = '';
else
    here = fileparts(mfilename('fullpath'));
    art  = fullfile(here, ['tire_coeffs_' p.car '.mat']);
    if ~exist(art, 'file')
        error('vehicle_params:noTireCoeffs', ...
              '%s not found for car %s. Run: build_tire_coeffs', ...
              ['tire_coeffs_' p.car '.mat'], p.car);
    end
    T = load(art);

    % --- artifact schema gate --------------------------------------------
    % Refuse an artifact written by older (or newer) code; the hash gate in
    % vd_selftest cannot tell that apart from a different tire.
    SCHEMA_EXPECTED = 2;
    have = 1;
    if isfield(T, 'schema_version'), have = T.schema_version; end
    if have ~= SCHEMA_EXPECTED
        error('vehicle_params:tireSchema', ...
            ['%s is schema v%g but this code expects v%d.\n' ...
             'The tire artifact predates the camber terms (or comes from newer ' ...
             'code).\nRun:  build_tire_coeffs'], ...
            ['tire_coeffs_' p.car '.mat'], have, SCHEMA_EXPECTED);
    end
    p.tire_schema_version = T.schema_version;

    p.mu_y_raw      = T.mu_y_raw;       % curve-based peak lateral mu @ design load
    p.mu_anisotropy = T.mu_anisotropy;  % mu_x/mu_y, computed cross-tire transfer
    p.Ca_coef       = T.Ca_coef;        % Ca(Fz) quadratic [lbf/deg]
    p.mu_coef       = T.mu_coef;        % mu(Fz) linear, valid only to Fz_fit_max
    p.Fz_fit_max    = T.Fz_fit_max;     % design tire's data edge [lbf]
    p.mu_hiload_slope = T.mu_hiload_slope; % donor-informed slope above the edge
    p.hiload_cov_lbf = T.hiload_cov_lbf;   % donor coverage limit [lbf] - past this, mu_of_load's 'central' slope is unvalidated even by donors
    p.Fz_outer_limit_lbf = T.Fz_outer_limit_lbf; % outer-tire cornering load [lbf] - computed once in build_tire_coeffs.m
    p.mu_outer_central   = T.mu_outer_central;   % mu at Fz_outer_limit_lbf, donor-informed
    p.mu_outer_low       = T.mu_outer_low;       % mu at Fz_outer_limit_lbf, pessimistic blind-linear
    p.shape6        = T.shape6;         % MF shape fraction at 6deg, load-matched to Fz_lat6
    p.mu_y_18_peak  = T.mu_y_18_peak;   % 18in LC0 lateral peak, back-derived from mu_y_at6/shape6
    p.mu_y_at6      = T.mu_y_at6;       % 18in LC0 measured mu_y at 6deg (raw, not peak)
    p.Fz_lat6       = T.Fz_lat6;        % load the 18in lateral data was actually taken at [lbf]
    p.mu_x_18       = T.mu_x_18;        % 18in LC0 mean drive/brake mu_x
    p.n_env_drive   = T.n_env_drive;    % friction-ellipse exponent, drive (measured 18in)
    p.n_env_brake   = T.n_env_brake;    % friction-ellipse exponent, brake (measured 18in)
    % Per-load-bin Magic Formula table - lets tire_forces build a whole curve.
    p.mf_bin_Fz_lbf = T.mf_bin_Fz_lbf;
    p.mf_bin_B      = T.mf_bin_B;
    p.mf_bin_C      = T.mf_bin_C;
    p.mf_bin_E      = T.mf_bin_E;
    % Camber sensitivity (models/tire_camber.m is the only evaluator).
    p.camber_kD            = T.camber_kD;
    p.camber_kC            = T.camber_kC;
    p.camber_kS            = T.camber_kS;
    p.camber_Fz_ref_lbf    = T.camber_Fz_ref_lbf;
    p.camber_Fz_min_lbf    = T.camber_Fz_min_lbf;
    p.camber_Fz_max_lbf    = T.camber_Fz_max_lbf;
    p.camber_gamma_max_deg = T.camber_gamma_max_deg;
    p.camber_status        = T.camber_status;
    p.camber_basis         = T.camber_basis;
    p.tire_basis    = T.basis;          % 'pacejka-curve'
    p.tire_src_hash = T.src_hash;       % what vd_selftest checks for staleness
end

% 'central' = donor-constrained, 'low' = pessimistic blind-linear. See mu_of_load.m.
% Meaningless in bootstrap mode (no grip curve loaded), so left unset there.
if ~bootstrap
    p.tire_hiload = 'central';
end

% ======================= DERIVED ========================================
% All derived quantities live in util/vd_derive.m (vd_set re-runs it).
p = vd_derive(p);
end