function C = camber_fit(data_dir, prefix, verbose)
% CAMBER_FIT  Camber sensitivity of one tire, from the TTC camber sweeps.
%   C = camber_fit(data_dir, prefix)          quiet-ish
%   C = camber_fit(data_dir, prefix, false)   no printing
%
% Called by pacejka_fit. Produces the three camber coefficient sets that
% tire_forces / mu_of_load consume. Theory: references/VD_physics_reference.md
% sec 8b.
%
% ---------------------------------------------------------------------------
% WHAT CAMBER DOES TO A TIRE (three separate effects, not one)
% ---------------------------------------------------------------------------
% 1. CAMBER THRUST. A leaning tire makes lateral force at ZERO slip angle,
%    because the contact patch is dragged along a cone rather than a cylinder.
%    Measured here as a horizontal SHIFT of the whole Fy(alpha) curve: the
%    curve still crosses zero, just at a non-zero slip angle. That is exactly
%    what the data shows, and it means camber buys you force at LOW slip
%    without changing the peak.
%
% 2. PEAK GRIP CHANGES. Leaning the tire loads one shoulder harder than the
%    other, so the pressure distribution across the contact patch is less
%    uniform and peak friction drops. In the Magic Formula this is a term in
%    gamma^2 - symmetric, always a penalty. But there is ALSO an asymmetric
%    part, linear in gamma, whose sign flips with load (see below).
%
% 3. CORNERING STIFFNESS DROPS. The slope of Fy vs alpha falls with camber
%    magnitude. Even in gamma (direction of lean does not matter).
%
% The "optimum camber" the suspension team wants is NOT a fitted parameter.
% It is where effect 1 stops paying for effect 2. It moves with load, and on
% THIS tire it moves right through zero: see the load dependence below.
%
% ---------------------------------------------------------------------------
% SIGN CONVENTION - read this before using gamma anywhere
% ---------------------------------------------------------------------------
%   gamma > 0  =  the tire leans so that camber thrust ADDS to the cornering
%                 force it is being asked to make (top of the tire tipped
%                 toward the corner centre).
%
% On a car in a steady corner the loaded OUTSIDE wheel wants gamma > 0. In the
% usual SAE chassis convention that is NEGATIVE camber on that wheel. The
% INSIDE wheel, on the same suspension, usually ends up at gamma < 0.
%
% The TTC rig only ever swept inclination angle POSITIVE (0, +2, +4 deg) and
% in its sign convention that is the ADVERSE direction - verified from the
% data, not assumed: at IA = +4, Fz ~ 150 lbf, the force at zero slip angle
% moves AWAY from the direction generated by positive slip angle. So this
% function MIRRORS the data (alpha -> -alpha, Fy -> -Fy) before fitting, which
% puts gamma > 0 on the helpful side.
%
% CONSEQUENCE, and it is a real limitation: there is no negative-inclination
% data at all. The adverse-camber branch is obtained by assuming the tire is
% symmetric. That assumption is checked at gamma = 0, where the two branches
% of the measured curve agree to about 2%.
%
% ---------------------------------------------------------------------------
% WHY THIS FILE HAS NO CURVE FIT IN IT
% ---------------------------------------------------------------------------
% pacejka_fit fits a 4-parameter Magic Formula because it needs the whole
% curve shape. Here we need only three numbers per condition - peak, zero
% crossing, low-slip slope - and all three can be read straight off the
% binned curve. A Magic Formula with shift terms would need 6 parameters and
% a bounded nonlinear solver, which can fail silently. Measuring the three
% quantities directly was also slightly MORE accurate in cross-validation
% (leave-one-load-out RMS 2.8% vs 3.4%), so there is no fidelity argument for
% the optimiser either.

if nargin < 3, verbose = true; end

% ---- fit setup ----------------------------------------------------------
C.Fz_ref_lbf = 150;        % normalising load for dfz = (Fz - Fz_ref)/Fz_ref.
                           % A MEASURED load bin, deliberately not the design
                           % load: the camber coefficients must not move when
                           % the car's mass changes.
LOAD_BINS_LBF = [50 100 150 200 250];
LOAD_BAND     = 0.15;      % +/-15% around each bin, same as pacejka_fit
SA_EDGES      = -12.25:0.5:12.25;   % SIGNED bins - see the warning below
MIN_BIN_N     = 10;        % samples needed to keep a slip-angle bin
MIN_CELL_N    = 300;       % samples needed for one (file, load, camber, P) cell
MIN_CURVE_PTS = 12;        % bins needed before a cell's curve is usable
V_MIN_MPH     = 20;        % ROLLING ONLY - see below
GAMMA_STEP    = 1.0;       % deg, resolution for finding the camber levels
P_STEP        = 2.0;       % psi, resolution for finding the pressure levels
MIN_LEVEL_N   = 2000;      % samples needed before a level counts as present

% ---- load and mask ------------------------------------------------------
D = load_camber_channels(data_dir, [prefix '_*.mat']);
if isempty(D.FZ)
    C = empty_result(C, 'no TTC files matched');
    return
end
Fz_lbf = -D.FZ;

% ROLLING ONLY. Some TTC runs include near-static segments (the design tire's
% file _1 is 99% below 5 mph). A tire that is not rolling generates almost no
% lateral force and NO camber thrust at all, so those samples would drag the
% camber terms toward zero. pacejka_fit's gamma=0 fit does not yet apply this
% filter - see the note it prints - so do not copy the mask from there.
rolling = (abs(D.FX ./ D.FZ) < 0.10) & (Fz_lbf > 30) & (D.V > V_MIN_MPH);

if nnz(rolling) < 5000
    C = empty_result(C, sprintf('only %d rolling pure-lateral samples', nnz(rolling)));
    return
end

gam_levels = discrete_levels(D.IA(rolling), GAMMA_STEP, MIN_LEVEL_N);
p_levels   = discrete_levels(D.P(rolling),  P_STEP,     MIN_LEVEL_N);
gam_levels = gam_levels(gam_levels >= 0);          % TTC swept one side only
if ~any(gam_levels == 0) || numel(gam_levels) < 2
    C = empty_result(C, 'no camber sweep found (need a zero level and at least one other)');
    return
end
C.gamma_levels_deg = gam_levels;
C.p_levels_psi     = p_levels;

% ---- build the per-cell response table ----------------------------------
% One "cell" is (file, load bin, camber level, pressure level). Everything is
% normalised to the gamma = 0 cell in the SAME file at the SAME load and
% pressure. That normalisation is the whole trick: the tire loses grip through
% a test session (this tire lost ~17% of peak lateral force between its own
% run 2 and run 3 at an identical condition), so absolute forces are not
% comparable across files - but a ratio taken inside one file and one pressure
% block is.
rowsD = zeros(0,3);   % [gamma, dfz, peak ratio]
rowsC = zeros(0,3);   % [gamma, dfz, cornering-stiffness ratio]
rowsS = zeros(0,3);   % [gamma, dfz, slip-angle offset, deg]
files = unique(D.file);

for fi = 1:numel(files)
  for k = 1:numel(LOAD_BINS_LBF)
    for pj = 1:numel(p_levels)
      cellsel = (D.file == files(fi)) & rolling ...
                & (abs(Fz_lbf - LOAD_BINS_LBF(k)) < LOAD_BINS_LBF(k)*LOAD_BAND) ...
                & (abs(D.P - p_levels(pj)) < P_STEP/2);

      M = cell(1, numel(gam_levels));
      Fz_cell = NaN;
      for gi = 1:numel(gam_levels)
          sel = cellsel & (abs(D.IA - gam_levels(gi)) < GAMMA_STEP/2);
          if nnz(sel) < MIN_CELL_N, break; end
          % MIRROR into the model convention (see the header). Do NOT
          % symmetrise the way pacejka_fit does - folding |SA| would cancel
          % camber thrust exactly, which is the thing we are trying to measure.
          [a, fy] = binned_signed_curve(-D.SA(sel), D.FY(sel), SA_EDGES, MIN_BIN_N);
          if numel(a) < MIN_CURVE_PTS, break; end
          M{gi} = curve_metrics(a, fy);
          if gi == 1, Fz_cell = mean(Fz_lbf(sel)); end
      end
      if any(cellfun(@isempty, M)), continue; end     % incomplete camber set

      base = M{1};                                    % gamma = 0
      dfz  = (Fz_cell - C.Fz_ref_lbf) / C.Fz_ref_lbf;
      for gi = 2:numel(gam_levels)
          g = gam_levels(gi);
          % Peak: +g reads the branch where thrust helps, -g the branch where
          % it hurts. One camber sweep therefore gives BOTH signs of gamma,
          % via the symmetry assumption stated in the header.
          if all(isfinite([M{gi}.pk_pos M{gi}.pk_neg base.pk_pos base.pk_neg]))
              rowsD(end+1,:) = [+g, dfz, M{gi}.pk_pos / base.pk_pos]; %#ok<AGROW>
              rowsD(end+1,:) = [-g, dfz, M{gi}.pk_neg / base.pk_neg]; %#ok<AGROW>
          end
          % Slip-angle offset: camber thrust as an equivalent slip angle.
          % Odd in gamma.
          if isfinite(M{gi}.a_zero) && isfinite(base.a_zero)
              d = -(M{gi}.a_zero - base.a_zero);
              rowsS(end+1,:) = [+g, dfz, +d]; %#ok<AGROW>
              rowsS(end+1,:) = [-g, dfz, -d]; %#ok<AGROW>
          end
          % Cornering stiffness: even in gamma.
          if isfinite(M{gi}.Ca) && isfinite(base.Ca)
              r = M{gi}.Ca / base.Ca;
              rowsC(end+1,:) = [+g, dfz, r]; %#ok<AGROW>
              rowsC(end+1,:) = [-g, dfz, r]; %#ok<AGROW>
          end
      end
    end
  end
end

if size(rowsD,1) < 8 || size(rowsS,1) < 8 || size(rowsC,1) < 4
    C = empty_result(C, sprintf(['too few complete camber cells (peak %d, ' ...
        'offset %d, stiffness %d rows)'], size(rowsD,1), size(rowsS,1), size(rowsC,1)));
    return
end

% ---- least squares ------------------------------------------------------
% Forms chosen by leave-one-load-bin-out and leave-one-file-out
% cross-validation on this tire's own data; the alternatives that were tried
% and rejected are listed in VD_physics_reference.md sec 8b.
%
%   peak factor        fD  = 1 + (kD1 + kD2*dfz + kD3*dfz^2)*gamma + kD4*gamma^2
%   stiffness factor   fC  = 1 + kC1*gamma^2
%   slip-angle offset  dSH = (kS1 + kS2*dfz)*gamma            [deg]
%
% The peak factor splits cleanly into two physical pieces, which is why it has
% the shape it does. Decomposing the measured ratios into their EVEN and ODD
% parts in gamma:
%
%   EVEN  (same whichever way the tire leans) = the contact-patch penalty.
%   Measured at -3.4% to -4.3% at gamma = 4 across EVERY load bin - flat in
%   load. That is the kD4*gamma^2 term, and it needs no load dependence
%   (adding one made the leave-one-file-out error worse).
%
%   ODD   (helps one way, hurts the other) = the direction-dependent part.
%   Measured +2.9% at 50 lbf and -2.9% at 250 lbf, at gamma = 2 - it CHANGES
%   SIGN with load. That is the (kD1 + kD2*dfz + kD3*dfz^2)*gamma term. It is
%   the whole reason camber is worth modelling and the whole reason a
%   load-independent camber term is useless: averaged over load it is
%   approximately zero, so it would predict that camber does nothing.
%   The dfz^2 term is there because the odd part FLATTENS above ~200 lbf; a
%   straight line in load overshot the 250 lbf bin by more than half
%   (leave-one-load-out RMS 0.023 -> 0.014 with the quadratic).
%
% The stiffness drop needs no load dependence at all. That asymmetry between
% the three effects is a result, not a modelling preference.
g = rowsD(:,1);  z = rowsD(:,2);
A = [g, g.*z, g.*z.^2, g.^2];  C.kD = (A \ (rowsD(:,3) - 1)).';
C.rms_peak   = rms_of(A*C.kD.' - (rowsD(:,3) - 1));

g = rowsC(:,1);
A = g.^2;                   C.kC = (A \ (rowsC(:,3) - 1)).';
C.rms_stiff  = rms_of(A*C.kC.' - (rowsC(:,3) - 1));

g = rowsS(:,1);  z = rowsS(:,2);
A = [g, g.*z];              C.kS = (A \ rowsS(:,3)).';
C.rms_offset = rms_of(A*C.kS.' - rowsS(:,3));

% ---- provenance and guard rails -----------------------------------------
C.n_peak    = size(rowsD,1);
C.n_stiff   = size(rowsC,1);
C.n_offset  = size(rowsS,1);
C.gamma_max_deg = max(gam_levels);          % never extrapolate camber past this
C.Fz_min_lbf    = min(LOAD_BINS_LBF);       % dfz is clamped to this range in
C.Fz_max_lbf    = max(LOAD_BINS_LBF);       % tire_forces - the load dependence
                                            % is a straight line and it must not
                                            % be run out to the outer-tire load
C.status  = 'ok';
C.basis   = 'ttc-camber-sweep, rolling only, within-file normalised';

if verbose
    fprintf('--- %s camber (%d/%d/%d rows; levels %s deg; %s psi)\n', prefix, ...
            C.n_peak, C.n_stiff, C.n_offset, mat2str(gam_levels), mat2str(p_levels));
    fprintf('      peak   fD  = 1 + (%+.5f %+.5f*dfz %+.5f*dfz^2)*g %+.6f*g^2  (RMS %.4f)\n', ...
            C.kD(1), C.kD(2), C.kD(3), C.kD(4), C.rms_peak);
    fprintf('      stiff  fC  = 1 %+.6f*g^2                          (RMS %.4f)\n', ...
            C.kC(1), C.rms_stiff);
    fprintf('      thrust dSH = (%+.5f %+.5f*dfz)*g deg              (RMS %.4f)\n', ...
            C.kS(1), C.kS(2), C.rms_offset);
end
end

% =========================================================================
function C = empty_result(C, why)
% A tire with no usable camber sweep gets coefficients that are exactly zero,
% not NaN. Zero means "camber changes nothing", which is what the model did
% before this file existed - so a missing sweep degrades to the old behaviour
% instead of poisoning every downstream number with NaN.
C.kD = [0 0 0 0];  C.kC = 0;  C.kS = [0 0];
C.rms_peak = NaN; C.rms_stiff = NaN; C.rms_offset = NaN;
C.n_peak = 0; C.n_stiff = 0; C.n_offset = 0;
C.gamma_levels_deg = 0;  C.p_levels_psi = [];
C.gamma_max_deg = 0;  C.Fz_min_lbf = NaN;  C.Fz_max_lbf = NaN;
C.status = ['none: ' why];
C.basis  = 'no camber data - camber terms disabled';
end

% =========================================================================
function lv = discrete_levels(x, step, min_n)
% The rig holds camber and pressure at discrete set points, but the recorded
% channels wander around them (hot pressure drifts, camber reads +/-0.03).
% Round to the set-point grid and keep the levels that actually have data.
r  = round(x(:) / step) * step;
u  = unique(r);
lv = u(arrayfun(@(v) nnz(r == v) >= min_n, u)).';
end

% =========================================================================
function [x, y] = binned_signed_curve(sa, fy, edges, min_n)
% Median force in each SIGNED slip-angle bin. Signed, not folded: the whole
% point of a camber fit is the left/right asymmetry that folding destroys.
% Medians (not means) because raw TTC sweeps carry hysteresis loops and
% junction artefacts that drag an average.
x = zeros(0,1); y = zeros(0,1);
for i = 1:numel(edges)-1
    m = (sa >= edges(i)) & (sa < edges(i+1));
    if nnz(m) > min_n
        x(end+1,1) = mean(sa(m));    %#ok<AGROW>
        y(end+1,1) = median(fy(m));  %#ok<AGROW>
    end
end
end

% =========================================================================
function m = curve_metrics(a, fy)
% Read the three numbers we need straight off one binned Fy(alpha) curve.
%   a  : signed slip angle [deg], model convention (positive alpha -> positive Fy)
%   fy : lateral force [lbf]
[a, k] = sort(a(:));  fy = fy(k);
pos = a >= 0;  neg = a <= 0;
m.pk_pos = local_peak(a(pos),  fy(pos));    % peak with camber thrust helping
m.pk_neg = local_peak(a(neg), -fy(neg));    % ... and with it hurting
m.a_zero = zero_crossing(a, fy);            % slip angle where Fy = 0
m.Ca     = low_slip_slope(a, fy, 1.5);      % [lbf/deg] near alpha = 0
end

function pk = local_peak(x, y)
% Largest sample, refined by a parabola through it and its neighbours - the
% bins are half a degree wide and the true peak usually sits between two.
if numel(y) < 3, pk = max(y); if isempty(pk), pk = NaN; end, return; end
[~, i] = max(y);
lo = max(1, i-2);  hi = min(numel(y), i+2);
if hi - lo < 2, pk = y(i); return; end
c = polyfit(x(lo:hi), y(lo:hi), 2);
pk = y(i);
if c(1) < 0
    xv = -c(2) / (2*c(1));
    if xv >= min(x(lo:hi)) && xv <= max(x(lo:hi)), pk = polyval(c, xv); end
end
end

function a0 = zero_crossing(a, fy)
% Where the curve crosses zero force. With no camber this is ~0 (a small
% offset is the tire's own plysteer/conicity). With camber it moves, and the
% MOVEMENT is the camber thrust expressed as an equivalent slip angle.
a0 = NaN;
s = sign(fy);  s(s == 0) = 1;
k = find(diff(s) ~= 0);
if isempty(k), return; end
[~, j] = min(abs(a(k)));          % the crossing nearest zero slip
i = k(j);
den = fy(i+1) - fy(i);
if den == 0, return; end
a0 = a(i) - fy(i) * (a(i+1) - a(i)) / den;
end

function Ca = low_slip_slope(a, fy, halfwidth_deg)
% Cornering stiffness: straight line through the bins within +/-1.5 deg.
% Wider than that and the curve is already bending over; narrower and there
% are not enough bins left to fit.
m = abs(a) <= halfwidth_deg;
if nnz(m) < 4, Ca = NaN; return; end
c  = polyfit(a(m), fy(m), 1);
Ca = c(1);
end

function r = rms_of(e)
r = sqrt(mean(e.^2));
end

% =========================================================================
function D = load_camber_channels(data_dir, pattern)
% Like pacejka_fit's load_channels, plus V (to drop non-rolling segments) and
% a file index (so ratios can be taken inside one run - see the degradation
% note in the body of camber_fit).
channels = {'SA','FY','FX','FZ','IA','P','V'};
files    = dir(fullfile(data_dir, pattern));
chunks   = cell(numel(files), numel(channels));
tags     = cell(numel(files), 1);
for i = 1:numel(files)
    if contains(files(i).name, 'raw'), continue; end
    S = load(fullfile(data_dir, files(i).name));
    if ~isfield(S, 'FZ'), continue; end
    for c = 1:numel(channels)
        if ~isfield(S, channels{c}), chunks{i,c} = []; break; end
        chunks{i,c} = S.(channels{c})(:);
    end
    if isempty(chunks{i,1}), continue; end
    tags{i} = i * ones(numel(S.FZ), 1);
end
for c = 1:numel(channels)
    D.(channels{c}) = vertcat(chunks{:,c});
end
D.file = vertcat(tags{:});
end
